const types = {
  SET_ITEM: '[ORDER] SET ITEM',
  SET_ITEMS: '[ORDER] SET ITEMS',
  UPDATE_ITEM: '[ORDER] UPDATE ITEM',
  REMOVE_ITEM: '[ORDER] REMOVE ITEM',
  CLEAR_ORDER: '[ORDER] CLEAR ORDER',
  SET_ORDERS: '[ORDER] SET ORDERS',
  SET_ACTIVE_ORDER: '[ORDER] SET ACTIVE ORDER',
  REMOVE_ACTIVE_ORDER: '[ORDER] REMOVE ACTIVE ORDER',
  REMOVE_ORDERS: '[ORDER] REMOVE ORDERS',
  UPDATE_ORDER: '[ORDER] UPDATE ORDER',
  DELETE_ORDER: '[ORDER] DELETE ORDER',
  ADD_ORDER: '[ORDER] ADD ORDER',
}

export default types
