const types = {
  SET_PRODUCTS: '[PRODUCT] SET PRODUCTS',
  UPDATE_PRODUCT: '[PRODUCT] UPDATE PRODUCT',
  DELETE_PRODUCT: '[PRODUCT] DELETE PRODUCT',
  ADD_PRODUCT: '[PRODUCT] ADD PRODUCT',
  SET_ACTIVE_PRODUCT: '[PRODUCT] SET ACTIVE PRODUCT',
  REMOVE_ACTIVE_PRODUCT: '[PRODUCT] REMOVE ACTIVE PRODUCT',
  SET_ORDER_ACTIVE_PRODUCT: '[PRODUCT] SET ORDER ACTIVE PRODUCT',
}

export default types
